### ISSUE TITLE
distance formula seems bugged ?

### ISSUE THREAD

**Issue by Totoleharicotvert** [iansedano/mars_lander#1]
Hello,
thank you very much for your code, i'm trying to resolve this puzzle in C++ (with a simulation ) and I needed some ideas to help find some solutions to simulate around.

I discovered your code which is interesting because of the 4 stages and for the distance's formula

nevertheless, I thing there is an issue in the calculation of the distance here : 
(vector_mag**2 / 2 * g)

I think the good formula is (vector_mag**2 / (2 * g))

perhaps it explain why you need to divide the distance by 10 after that => (3,711 * 3,711) = 13,77

Thanks !

**Comment by iansedano** [comment]
You're right! I just tested the code with your ammendment and the lander works. Excellent! I remember spending a long time staring at it trying to figure out what I'd done wrong. Thank you.

Thanks for the comment and very glad that it could be of some use.

**Comment by Totoleharicotvert** [comment]
> You're right! I just tested the code with your ammendment and the lander works. Excellent! I remember spending a long time staring at it trying to figure out what I'd done wrong. Thank you.
> 
> 
> 
> Thanks for the comment and very glad that it could be of some use.

Thank you very much ! Have a good day 😉
